/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package christmas_card_ufu;

public class App {

    public static void main(String[] args) {

        Widget card = new ChristmasText();
        card = new Margin(1, 2, card);
        card = new Heart(card);
        card = new Repeat(card, 2);
        card.build();

        for (int i = 0; i < 5; i++) {
            card = new ChristmasText();
            card = new Margin(1, i + 2, card);
            card = new Repeat(card, i);
            card = new Heart(card);
            card.build();
        }

    }
}