/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package christmas_card_ufu;

public class App {

    public static void main(String[] args) {

        String[] texts = {"Mamãe te amo", "EU AMO PÃO DE QUEIJO", "PÃO DE QUEIJO COM PANETTONE!", "shrek is:"};
        Widget body = new Heart();
        for (String text : texts) {
            Widget header = new Text(text);
            ChristmasCard card = new ChristmasCard(header, body);
            card.build();
        }

        Widget header = new Text("Querido Professor, por favor considerar dar nota 10 nesse trabalho");
        ChristmasCard card = new ChristmasCard(header, body);
        card.build();
    }
}